// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OidcProvider is the predicate function for oidcprovider builders.
type OidcProvider func(*sql.Selector)
