@startuml
SUBMITTED --> REJECTED : REJECT
SUBMITTED --> PROCESSING : APPROVE
REJECTED --> DRAFT : REVISE
REJECTED --> SUBMITTED : WITHDRAW
DRAFT --> SUBMITTED : SUBMIT
PUBLISHED --> UNPUBLISHED : UNPUBLISH
PROCESSING --> PUBLISHED : PUBLISH
UNPUBLISHED --> PUBLISHED : PUBLISH
@enduml
