// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"oidc/ent/migrate"

	"oidc/ent/oidcprovider"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"

	"oidc/ent/internal"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OidcProvider is the client for interacting with the OidcProvider builders.
	OidcProvider *OidcProviderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OidcProvider = NewOidcProviderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		// schemaConfig contains alternative names for all tables.
		schemaConfig SchemaConfig
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.schemaConfig = DefaultSchemaConfig
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		OidcProvider: NewOidcProviderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		OidcProvider: NewOidcProviderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OidcProvider.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.OidcProvider.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.OidcProvider.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OidcProviderMutation:
		return c.OidcProvider.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OidcProviderClient is a client for the OidcProvider schema.
type OidcProviderClient struct {
	config
}

// NewOidcProviderClient returns a client for the OidcProvider from the given config.
func NewOidcProviderClient(c config) *OidcProviderClient {
	return &OidcProviderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oidcprovider.Hooks(f(g(h())))`.
func (c *OidcProviderClient) Use(hooks ...Hook) {
	c.hooks.OidcProvider = append(c.hooks.OidcProvider, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oidcprovider.Intercept(f(g(h())))`.
func (c *OidcProviderClient) Intercept(interceptors ...Interceptor) {
	c.inters.OidcProvider = append(c.inters.OidcProvider, interceptors...)
}

// Create returns a builder for creating a OidcProvider entity.
func (c *OidcProviderClient) Create() *OidcProviderCreate {
	mutation := newOidcProviderMutation(c.config, OpCreate)
	return &OidcProviderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OidcProvider entities.
func (c *OidcProviderClient) CreateBulk(builders ...*OidcProviderCreate) *OidcProviderCreateBulk {
	return &OidcProviderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OidcProviderClient) MapCreateBulk(slice any, setFunc func(*OidcProviderCreate, int)) *OidcProviderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OidcProviderCreateBulk{err: fmt.Errorf("calling to OidcProviderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OidcProviderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OidcProviderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OidcProvider.
func (c *OidcProviderClient) Update() *OidcProviderUpdate {
	mutation := newOidcProviderMutation(c.config, OpUpdate)
	return &OidcProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OidcProviderClient) UpdateOne(op *OidcProvider) *OidcProviderUpdateOne {
	mutation := newOidcProviderMutation(c.config, OpUpdateOne, withOidcProvider(op))
	return &OidcProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OidcProviderClient) UpdateOneID(id int) *OidcProviderUpdateOne {
	mutation := newOidcProviderMutation(c.config, OpUpdateOne, withOidcProviderID(id))
	return &OidcProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OidcProvider.
func (c *OidcProviderClient) Delete() *OidcProviderDelete {
	mutation := newOidcProviderMutation(c.config, OpDelete)
	return &OidcProviderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OidcProviderClient) DeleteOne(op *OidcProvider) *OidcProviderDeleteOne {
	return c.DeleteOneID(op.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OidcProviderClient) DeleteOneID(id int) *OidcProviderDeleteOne {
	builder := c.Delete().Where(oidcprovider.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OidcProviderDeleteOne{builder}
}

// Query returns a query builder for OidcProvider.
func (c *OidcProviderClient) Query() *OidcProviderQuery {
	return &OidcProviderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOidcProvider},
		inters: c.Interceptors(),
	}
}

// Get returns a OidcProvider entity by its id.
func (c *OidcProviderClient) Get(ctx context.Context, id int) (*OidcProvider, error) {
	return c.Query().Where(oidcprovider.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OidcProviderClient) GetX(ctx context.Context, id int) *OidcProvider {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OidcProviderClient) Hooks() []Hook {
	return c.hooks.OidcProvider
}

// Interceptors returns the client interceptors.
func (c *OidcProviderClient) Interceptors() []Interceptor {
	return c.inters.OidcProvider
}

func (c *OidcProviderClient) mutate(ctx context.Context, m *OidcProviderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OidcProviderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OidcProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OidcProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OidcProviderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OidcProvider mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		OidcProvider []ent.Hook
	}
	inters struct {
		OidcProvider []ent.Interceptor
	}
)

var (
	// DefaultSchemaConfig represents the default schema names for all tables as defined in ent/schema.
	DefaultSchemaConfig = SchemaConfig{
		OidcProvider: tableSchemas[0],
	}
	tableSchemas = [...]string{"oidc"}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *config) {
		c.schemaConfig = schemaConfig
	}
}
