[versions]
quarkus = "3.30.4"
carl = '1.0-BATE'
testcontainers = "1.20.4"
[libraries]
quarkus-platform-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
infra-component-dto = { module = "org.carl:infra-component-dto", version.ref = "carl" }
infra-component-authorization = { module = "org.carl:infra-component-authorization", version.ref = "carl" }
infra-component-cache = { module = "org.carl:infra-component-cache", version.ref = "carl" }
infra-component-quarkus-persistence = { module = "org.carl:infra-component-quarkus-persistence", version.ref = "carl" }
infra-component-persistence-jooq = { module = "org.carl:infra-component-persistence-jooq", version.ref = "carl" }
infra-component-search = { module = "org.carl:infra-component-search", version.ref = "carl" }
infra-component-web = { module = "org.carl:infra-component-web", version.ref = "carl" }
infra-component-qdrant-grpc = { module = "org.carl:infra-component-qdrant-grpc", version.ref = "carl" }
infra-component-embedding-grpc = { module = "org.carl:infra-component-embedding-grpc", version.ref = "carl" }
infra-component-workflow = { module = "org.carl:infra-component-workflow", version.ref = "carl" }
infra-component-statemachine = { module = "org.carl:infra-component-statemachine", version.ref = "carl" }
infra-component-metrics = { module = "org.carl:infra-component-metrics", version.ref = "carl" }
infra-component-mq = { module = "org.carl:infra-component-mq", version.ref = "carl" }
infra-component-redis = { module = "org.carl:infra-component-redis", version.ref = "carl" }
infra-component-ruleengine = { module = "org.carl:infra-component-ruleengine", version.ref = "carl" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-consul = { module = "org.testcontainers:consul", version.ref = "testcontainers" }
testcontainers-pulsar = { module = "org.testcontainers:pulsar", version.ref = "testcontainers" }
testcontainers-neo4j = { module = "org.testcontainers:neo4j", version.ref = "testcontainers" }
testcontainers-elasticsearch = { module = "org.testcontainers:elasticsearch", version.ref = "testcontainers" }
testcontainers-milvus = { module = "org.testcontainers:milvus", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
quarkus-grpc = { module = "io.quarkus:quarkus-grpc", version.ref = "quarkus" }

quarkus-flyway = { module = "io.quarkus:quarkus-flyway", version.ref = "quarkus" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5", version.ref = "quarkus" }
assured = { module = "io.rest-assured:rest-assured", version.ref = "quarkus" }

[bundles]
all = [
    'infra-component-authorization',
    'infra-component-cache',
    'infra-component-quarkus-persistence',
    'infra-component-search',
    'infra-component-web',
]


test = [
    'quarkus-flyway',
    'assured',
    'quarkus-junit5',
    # 'testcontainers-junit-jupiter',
    # 'testcontainers',
    # 'testcontainers-postgresql',
    # 'testcontainers-pulsar',
    # 'testcontainers-consul',
    # 'testcontainers-neo4j',
    # 'testcontainers-elasticsearch',
    # 'testcontainers-milvus'
]
[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
