// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OidcProviderColumns holds the columns for the "oidc provider" table.
	OidcProviderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "oidc_provider_id", Type: field.TypeInt64, Unique: true, Comment: "OidcProvider ID"},
		{Name: "oidc_provider_name", Type: field.TypeString, Comment: "OidcProvider Name", Default: "unknown"},
		{Name: "oidc_provider_description", Type: field.TypeString, Nullable: true, Comment: "OidcProvider Description"},
		{Name: "issuer", Type: field.TypeString, Comment: "issuer"},
		{Name: "proxy_url", Type: field.TypeString, Nullable: true, Comment: "proxy URL"},
		{Name: "client_id", Type: field.TypeString, Comment: "Client ID"},
		{Name: "client_secret", Type: field.TypeString, Comment: "Client Secret"},
		{Name: "redirect_uri", Type: field.TypeString, Comment: "Redirect URI"},
		{Name: "endpoints", Type: field.TypeJSON, Nullable: true, Comment: "OidcProvider Endpoints"},
	}
	// OidcProviderTable holds the schema information for the "oidc provider" table.
	OidcProviderTable = &schema.Table{
		Name:       "oidc provider",
		Columns:    OidcProviderColumns,
		PrimaryKey: []*schema.Column{OidcProviderColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oidcprovider_oidc_provider_id",
				Unique:  true,
				Columns: []*schema.Column{OidcProviderColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OidcProviderTable,
	}
)

func init() {
	OidcProviderTable.Annotation = &entsql.Annotation{
		Table: "oidc provider",
	}
}
